:Author: apitech
:Email:
:Date: 19/09/2024
:Revision: version#
:License: Public Domain

= Project: {Project}

Describe your project

== Step 1: Installation
1.Download this file 
2. open the file on Arduino ide
== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact: 

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Quantity
| R1 | 100 ohms Resistor    | 1      
| L1 | Red LED           | 1  
| L2 | Yellow LED        | 1  
| L3 | Green LED        | 1
| E1 | Esp 32    | 1    
| s1 | servo motor |1
| u1 | HC-SR04 | 1


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
