// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "a04f7644-4794-438f-8abc-456f7b1c1f5f";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onGREENChange();
void onREDChange();
void onULTRASONICChange();

CloudSwitch gREEN;
CloudSwitch rED;
CloudLength uLTRASONIC;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gREEN, READWRITE, ON_CHANGE, onGREENChange);
  ArduinoCloud.addProperty(rED, READWRITE, ON_CHANGE, onREDChange);
  ArduinoCloud.addProperty(uLTRASONIC, READWRITE, ON_CHANGE, onULTRASONICChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
