// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "81d49e0e-be2a-40cf-89c9-93d60494f0fc";

const char SSID[]               = "DeeThunder";    // Network SSID (name)
const char PASS[]               = "Deetunda@20";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "wgX!NB?LrmTZSyGAq@sTfan@k";    // Secret device password


String gpslocationCloud;
float distanceCloud;
bool accidentDetectedCloud;
bool gasLeakCloud;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(gpslocationCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(distanceCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(accidentDetectedCloud, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gasLeakCloud, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
