// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1b53c8e5-e685-411a-a3e1-8833017ec968";

const char SSID[]               = "DeeThunder" ;    // Network SSID (name)
const char PASS[]               = "Deetunda15";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "3QAsIBM79WzFPwNJI#Zb@SKuD";    // Secret device password

void onLedChange();

CloudLight led;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(led, READWRITE, ON_CHANGE, onLedChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
