#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/b6cbc345-3fde-41a9-96e7-4d821307655e 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudLight gREEN;
  CloudLight rED;
  CloudLight yELLOW;
  CloudLength uLTRASONIC;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <HCSR04.h>
// #include <HTTPClient.h>
// #include <UrlEncode.h>

UltraSonicDistanceSensor distanceSensor(5, 18);

const int trigPin =5;
const int echoPin =18;

#define SOUND_SPEED 0.034

long duration;

// String phoneNumber = "+2349035320980";
// String apiKey = "2881429";

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  pinMode(trigPin, OUTPUT); 
  pinMode(echoPin, INPUT);
  pinMode(13, OUTPUT);
  pinMode(27, OUTPUT);
  pinMode(26, OUTPUT);

}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  digitalWrite(trigPin, LOW); //clears the trigpin
  delayMicroseconds(2);
  
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  duration = pulseIn (echoPin, HIGH);
  uLTRASONIC = duration * SOUND_SPEED/2;
  Serial.print("Distance(cm): ");
  Serial.println(uLTRASONIC);
    if(uLTRASONIC >= 11.00){
      digitalWrite(13, HIGH);
      digitalWrite(27, LOW);
      digitalWrite(26, LOW);
    Serial.println("low WATER LEVEL");
  }
  else if ((uLTRASONIC <=10.59) && (uLTRASONIC >=2.51) ) {
    digitalWrite(13, LOW);
      digitalWrite(27, HIGH);
      digitalWrite(26, LOW);
    Serial.println("AVERAGE WATER LEVEL");
  }
  else if(uLTRASONIC <=2.50){
    digitalWrite(13, LOW);
      digitalWrite(27, LOW);
      digitalWrite(26, HIGH);
    Serial.println("FULL WATER LEVEL");
  }
  delay(1000);

}


/*
  Since RED is READ_WRITE variable, onREDChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onREDChange()  {
  // Add your code here to act upon RED 
  // if (digitalRead(13== HIGH)){
  //   sendMessage("Water level is low");
  // }
   
}
/*
  Since YELLOW is READ_WRITE variable, onYELLOWChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onYELLOWChange()  {
  // Add your code here to act upon YELLOW change

}
/*
  Since GREEN is READ_WRITE variable, onGREENChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onGREENChange()  {
  // Add your code here to act upon GREEN change
//    if (digitalRead(26== HIGH)){
//     sendMessage("Water level is HIGH");
//   }
}

/*
  Since ULTRASONIC is READ_WRITE variable, onULTRASONICChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onULTRASONICChange()  {
  // Add your code here to act upon ULTRASONIC change

}
// void sendMessage(String message){

//   // Data to send with HTTP POST
//   String url = "https://api.callmebot.com/whatsapp.php?phone=" + phoneNumber + "&apikey=" + apiKey + "&text=" + urlEncode(message);    
//   httpClient http;
//   http.begin(url);

//   // Specify content-type header
//   http.addHeader("Content-Type", "application/x-www-form-urlencoded");
  
//   // Send HTTP POST request
//   int httpResponseCode = http.POST(url);
//   if (httpResponseCode == 200){
//     Serial.print("Message sent successfully");
//   }
//   else{
//     Serial.println("Error sending the message");
//     Serial.print("HTTP response code: ");
//     Serial.println(httpResponseCode);
//   }

//   // Free resources
//   http.end();
// }
